# Wrangler configuration for TextArtTools MCP Server
name = "textarttools-mcp"
main = "dist/index.js"
compatibility_date = "2025-01-20"
compatibility_flags = ["nodejs_compat"]

# Default configuration
workers_dev = false

# Worker configuration
[env.production]
name = "textarttools-mcp"
routes = [
  "mcp.textarttools.com/*"
]

# Environment variables for production
[env.production.vars]
ENVIRONMENT = "production"
CORS_ORIGIN = "*"
RATE_LIMIT_PER_MINUTE = "100"
MAX_TEXT_LENGTH = "10000"

# Security configuration
SECURITY_LEVEL = "standard"
CSP_REPORT_ENDPOINT = "/csp-report"

# KV namespaces for production
[[env.production.kv_namespaces]]
binding = "MCP_SESSIONS"
id = "8aa4da475e344c39818fc2dc721354fd"

# R2 bucket for figlet fonts
[[env.production.r2_buckets]]
binding = "FIGLET_FONTS"
bucket_name = "textarttools-figlet-fonts"

[env.development]
name = "textarttools-mcp-dev"

# Environment variables for development
[env.development.vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "*"
RATE_LIMIT_PER_MINUTE = "100"
MAX_TEXT_LENGTH = "10000"

# Security configuration (permissive for development)
SECURITY_LEVEL = "permissive"

# KV namespaces for development
[[env.development.kv_namespaces]]
binding = "MCP_SESSIONS"
preview_id = "7b6cceb7f62f49abb89f9decdeac9bdb"

# R2 bucket for figlet fonts (development)
[[env.development.r2_buckets]]
binding = "FIGLET_FONTS"
bucket_name = "textarttools-figlet-fonts"

# Secrets to be set with `wrangler secret put <name>`
# GITHUB_CLIENT_ID = "your_github_oauth_client_id"
# GITHUB_CLIENT_SECRET = "your_github_oauth_client_secret"
# JWT_SECRET = "your_jwt_secret_for_token_signing"

# Analytics and monitoring (configure for production deployment)
# [[analytics_engine_datasets]]
# binding = "MCP_ANALYTICS"
# dataset = "textarttools_mcp_usage"

# Durable Objects (if needed for advanced session management)
# [[durable_objects.bindings]]
# name = "SESSION_MANAGER"
# class_name = "SessionManager"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Development configuration
[dev]
port = 8788
local_protocol = "http"

# Limits (only available on paid plans)
# [limits]
# cpu_ms = 30000